# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6e7eb94695e16123cc2ac0a6ec6143622589d025aa7063d3e697ce91cf44a3540bea6b7e07e4e7845e195c999f8861b9382b560fd245b96946d8be6d192854f4

test:
  secret_key_base: cb031818696adc050c8955532e9e6fb7dbf913875f85a420518068b629bf90fb307c7f0e1bde0f1f4d95f9b6d0ec5b5138c00f26e06d5a7d16240726201b5d57

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
